### PR TITLE
Increase max ICE candidates to 128

### PR DESCRIPTION
**Pull request by ruffrey**
The following issue still happens while running chan_respoke on docker behind a NAT. Signaling seems good, but an error happens on asterisk as well as in the web browser. This was suggested by Matt Jordan as a possible fix.

asterisk:

``` plain
[Aug  5 14:26:12] WARNING[109]: res_rtp_asterisk.c:784 ast_rtp_ice_start: Failed to create ICE session check list: Too many objects of the specified type (PJ_ETOOMANY) (0x7f9fb004b4f8)
```

chrome 51.0.2704.103 (64-bit)

``` plain
...
[Respoke] PC handleAnswerSignal Object {signal: Object, name: "signal-answer", target: Object}
respoke.min.js:2 [Respoke] got answer Object {answer: "final", signalType: "answer", version: "1.0", sessionId: "5743E90E-3919-4156-B9AA-419BE8CE8B09", parsedSDP: Object…}
respoke.min.js:2 [Respoke] Call handleAnswerSignal Object {signal: Object, name: "signal-answer", target: Object}
respoke.min.js:2 [Respoke] Exception calling setRemoteDescription on answer I received. DOMException: Failed to set remote answer sdp: Called in wrong state: STATE_INPROGRESS(anonymous function) @ respoke.min.js:2errorHandler @ respoke.min.js:41
respoke.min.js:2 [Respoke] fired respoke.Call#error 0 listeners called with params Object {message: "Exception calling setRemoteDescription on answer I received.", name: "error", target: Object}
respoke.min.js:2 [Respoke] set remote desc of answer failed Object {sdp: "v=0
↵o=- 431878786 2 IN IP4 0.0.0.0
↵s=Asterisk
↵t…4994 typ relay raddr 50.173.112.172 rport 57829
↵", type: "answer"} DOMException: Failed to set remote answer sdp: Called in wrong state: STATE_INPROGRESS(anonymous function) @ respoke.min.js:2errorHandler @ respoke.min.js:41
respoke.min.js:2 [Respoke] sending hangup
...
```

### CODE REVIEW

**Comment by leedm777** [comment]
@ruffrey Do you know how many ICE candidates you were receiving?

**Comment by chadxz** [comment]
in our chat he said 

> 26 from the browser and 12 from asterisk

**Comment by leedm777** [comment]
Then it's probably `PJ_ICE_MAX_CHECKS` that's too low. The theoretical max is `PJ_ICE_MAX_CAND * PJ_ICE_MAX_CAND`, but that sort of geometric explosion is typically a Bad Thing™.

Maybe try a much larger multiplier, like `PJ_ICE_MAX_CAND * 16`.

**Comment by ruffrey** [comment]
Thanks so much for weighing in, @leedm777 ! I will do what you said, instead.

**Comment by leedm777** [comment]
:+1:, assuming it actually works.

**Comment by chadxz** [comment]
The recommended way to install pjsip for Asterisk now is to pass `--with-pjproject-bundled` flag to Asterisk's `./configure` script. Along with downloading pjsip automatically for you and installing it with the right options, it will pull in a config_site.h optimized for Asterisk, including settings to help WebRTC behave.

**Pull request closed without merging**
